### PR TITLE
bfs and scc

### PR DESCRIPTION
**Pull request by jitwit**
Hey. Following up the discussions at alga, this is to start to add `bfs` and `scc` to the regression suites. Is this the right approach? What else should be added?

### CODE REVIEW

**Comment by snowleopard** [comment]
@jitwit I guess for this to work, you'll need to modify the Cabal file to point to the Alga HEAD instead of Hackage, at least until the new version of Alga is released.

**Comment by nobrakal** [comment]
Hi,

This is the right approach :)

As mentioned, you should change the [`stack.yaml`](https://github.com/haskell-perf/graphs/blob/master/stack.yaml) to use the alga HEAD.

**Comment by jitwit** [comment]
Ah! I'm so used to using cabal I forgot to consider the stack.yaml file

**Comment by nobrakal** [comment]
I am not very happy with the type returned by `scc` since it will not be easy to compare with the one from `Data.Graph`. I am merging this anyway, since it is useful on its own.

Thanks :)

**Comment by jitwit** [comment]
Yeah, I'm working on getting an AdjacencyIntMap version together. Hopefully it will have a more reasonable type soon :)

**Pull request merged**
